version: '3.8'

services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: trellol-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: trellol-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
